export const FEEDBACK_WEIGHTS = {
  HALF_LIFE_DAYS: 90,

  MIN_USERS_FOR_SIGNAL: 2,
  MIN_SAME_USER_REPEATS: 3,

  BELOW_CONSENSUS_WEIGHT: 0.5,
  NON_DATA_OVERRIDE_WEIGHT: 0.5,

  MAX_FEEDBACK_LOOKBACK_DIRECT: 500,
  MAX_FEEDBACK_LOOKBACK_GLOBAL: 1000,

  MAX_TAT_BOOST: 20,
  MAX_SPECIALTY_BOOST: 20,
  MAX_ESCALATION_BOOST: 20,

  PROVEN_PAIRING_BONUS: 12,
  REASSIGNED_SCORE_CAP: 40,
  REASSIGNMENT_PENALTY: 10,

  GLOBAL_BASELINE_WEIGHT: 0.3,
  MIN_DIRECT_FEEDBACK_FOR_FULL_WEIGHT: 3,

  COVERAGE_TARGET_PCT: 80,
  COVERAGE_WARNING_PCT: 50,

  ROLLING_WINDOW_DAYS: 60,
  ROLLING_MIN_SAMPLES: 2,

  PENALTY_DECAY_DAYS: 90,
  PENALTY_DECAY_HALF_LIFE: 0.5,
} as const;
